name: wanandroid_flutter
description: Flutter版&quot;玩Android&quot;

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.7
  path_provider: ^1.1.0
  device_info: ^0.4.0+2
  shared_preferences: ^0.5.3+1
  json_annotation: ^2.4.0
  bloc: ^0.14.4
  flutter_bloc: ^0.18.3
  equatable: ^0.2.6
  cached_network_image: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.5
  url_launcher: ^5.1.0
  flare_flutter: ^1.5.4
  package_info: 0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.0.0
  build_runner: ^1.6.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # 安卓图片大小对应关系：1.5X=hdpi 2.0x=xhdpi 3.0x=xxhdpi 4.0x=xxxhdpi
  assets:
    - images/ic_launcher.png
    - images/todo_bg.jpeg
    - images/pull.png
    - images/add.png
    - images/finish.png
    - images/user_icon.jpeg
    - images/new.png
    - images/baitu.png
    - images/bianfu.png
    - images/bianselong.png
    - images/daishu.png
    - images/daxiang.png
    - images/eyu.png
    - images/gongji.png
    - images/gou.png
    - images/hainiu.png
    - images/haiyaoyu.png
    - images/hashiqi.png
    - images/hema.png
    - images/houzi.png
    - images/huanxiong.png
    - images/hudie.png
    - images/jiakechong.png
    - images/jingangyingwu.png
    - images/jingyu.png
    - images/juzuiniao.png
    - images/laohu.png
    - images/laoshu.png
    - images/luotuo.png
    - images/mao.png
    - images/maotouying.png
    - images/mianyang.png
    - images/milu.png
    - images/nainiu.png
    - images/pangxie.png
    - images/qie.png
    - images/qingwa.png
    - images/shayu.png
    - images/she.png
    - images/shiyishou.png
    - images/shizi.png
    - images/shuta.png
    - images/songshu.png
    - images/tiane.png
    - images/tihu.png
    - images/tuoniao.png
    - images/wugui.png
    - images/drawer_bg.jpeg
    - images/rocket.png
    - images/wechat.png
    - images/ccy_pay_qr.jpeg
    - images/nice_xiongdei.jpeg
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Stiff
      fonts:
        - asset: assets/fonts/font_stiff.ttf
